### ISSUE TITLE
MODX Revo?

### ISSUE THREAD

**Issue by ghost** [Nicola1971/OCx#2]
How difficult would it be to get this to work with MODX Revo out of curiosity?

Thanks,

**Comment by Nicola1971** [comment]
Hi, 
I've made a little test for you:
Snippets requires only a couple of modification, to work with revo

for the module is not so simple, because Modules does not exist in Revo, so i need to convert to a Revo CMP 

anyway, you can test this Revo version of snippets.
https://github.com/Nicola1971/OCx-Revo

Copy and paste the code from snippets:
https://github.com/Nicola1971/OCx-Revo/tree/master/install/snippets

Create a chunk and paste the code from this chunk :
https://github.com/Nicola1971/OCx-Revo/tree/master/install/chunks

Copy ocx files folder
 https://github.com/Nicola1971/OCx-Revo/tree/master/assets/components
 in assets/components/

in addition to the Evo call

```
[[OCxCategory? &cat=`3` &opencartTpl=`opencartTpl` &limit=`50` &fetchimages=`0` &orderby=`price` &orderdir=`DESC` &store_dir=`assets/images/ocx`]]
```

Without ocx module, You have to pass db configuration parameters in snippet call 

```
&oc_db_hostname=`localhost` &oc_db_username =`root` &oc_db_password =`yourpassword` &oc_db_database =`opencart2` 

```

or hard code in snippet code
https://github.com/Nicola1971/OCx-Revo/blob/master/install/snippets/OCxProduct.tpl#L22-L25

NOTE: tested only OCxProduct snippet, but everything works

**Comment by lkfranklin** [comment]
Wow. Thank you! That was really unexpected. I'll give these a go shortly.

Are you taking on development projects at the moment? I have a more in depth MODX/OC requirement if you're taking on work?

Thanks,
